name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v2
      - name: Log environments
        run: |
          echo "Logging GitHub environments"
          echo "Branch" ${GITHUB_REF##*/}
          echo "GITHUB_REPOSITORY_NAME_SLUG" ${GITHUB_REPOSITORY_NAME_SLUG}
          echo "GITHUB_REF" ${GITHUB_REF}
          echo "GITHUB_REF_NAME" ${GITHUB_REF_NAME}
          echo "GITHUB_REF_NAME_SLUG" ${GITHUB_REF_NAME_SLUG}
          echo "GITHUB_REF_SLUG" ${GITHUB_REF_SLUG}

      - name: npm install, build and test
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: ./scripts/check-file.sh
      - run: npm install -g auto-changelog
        env:
          CI: true
          FILE: ./dist/anywhere-webcomponents/anywhere-webcomponents.js

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: output/test/code-coverage.html

  deploy:
    name: Distribute to NPM and CDN
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2

      # NPM PUBLISH
      - name: Publish to NPM if version has been updated
        uses: pascalgn/npm-publish-action@51fdb4531e99aac1873764ef7271af448dc42ab4
        continue-on-error: true
        with:
          tag_name: v%s
          tag_message: v%s
          commit_pattern: ^[Rr]elease (\\S+)
        env: # More info about the environment variables in the README
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this as is, it's automatically generated
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # You need to set this in your repo settings

      - name: Configure AWS credentials for CDN account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          aws-region: sa-east-1
      - name: Copy files to S3
        run: aws s3 sync dist s3://cdn.tiagoboeing.com/anywhere-webcomponents/${GITHUB_REF##*/} --delete
      - name: Invalidate cache on CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DIST_ID }} --paths "/anywhere-webcomponents/${GITHUB_REF##*/}/*"

  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      # Auto changelog
      - name: Generate auto-changelog command
        uses: actions/setup-node@v1
      - run: npm run changelog
      - name: Commit auto-changelog changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: GitHub Workflow
          author_email: contato@tiagoboeing.com
          message: "[Automatic] Changelog generated"
          add: "CHANGELOG.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
