name: Deploy (develop)

on:
  push:
    branches: [develop]

jobs:
  deploy_CDN:
    name: Build and distribute
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm install -g auto-changelog

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: GitHub Workflow
          author_email: contato@tiagoboeing.com
          message: "[Automatic] Changelog generated"
          add: "CHANGELOG.md"
        env:
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN_GITHUB}}
